version: '3.6'
services:
  storage_emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    # image: microsoft/azure-storage-emulator
    container_name: azure-storage-emulator
    ports:
       - 10000:10000
       - 10001:10001
      #  - 10002:10002
    networks:
      - fractal

networks:
  fractal:
    driver: bridge


